/**
* File was generated by animation packager.
*/
#ifndef		_EFFECT_COMBO_01_I6_H
#define		_EFFECT_COMBO_01_I6_H


#define		EFFECT_COMBO_01_I6_NUM_MODULES				2
#define		EFFECT_COMBO_01_I6_MODULE_FX				0
#define		EFFECT_COMBO_01_I6_MODULE_FX_2				1


#define		EFFECT_COMBO_01_I6_NUM_FRAMES				2


#define		EFFECT_COMBO_01_I6_NUM_ANIMS				0


#endif