/**
* File was generated by animation packager.
*/
#ifndef		_EFFECT_LIGHT_01_I6_H
#define		_EFFECT_LIGHT_01_I6_H


#define		EFFECT_LIGHT_01_I6_NUM_MODULES				9
#define		EFFECT_LIGHT_01_I6_MODULE_LIGHT_2				0
#define		EFFECT_LIGHT_01_I6_MODULE_CIRCLE				2
#define		EFFECT_LIGHT_01_I6_MODULE_LIGHT				4
#define		EFFECT_LIGHT_01_I6_MODULE_WHITE				6


#define		EFFECT_LIGHT_01_I6_NUM_FRAMES				8


#define		EFFECT_LIGHT_01_I6_NUM_ANIMS				0


#endif