/**
* File was generated by animation packager.
*/
#ifndef		_FONT_21PX_200_H
#define		_FONT_21PX_200_H


#define		FONT_21PX_200_NUM_MODULES				99


#define		FONT_21PX_200_NUM_FRAMES				103
#define		FONT_21PX_200_FRAME_1				4
#define		FONT_21PX_200_FRAME_6				5
#define		FONT_21PX_200_FRAME_/				14
#define		FONT_21PX_200_FRAME_~				93
#define		FONT_21PX_200_FRAME_HEART				95
#define		FONT_21PX_200_FRAME_FOOD				97
#define		FONT_21PX_200_FRAME_VACCINE				98
#define		FONT_21PX_200_FRAME_HEART_W				100
#define		FONT_21PX_200_FRAME_FOOD_W				101
#define		FONT_21PX_200_FRAME_VACCINE_W				102


#define		FONT_21PX_200_NUM_ANIMS				0


#endif