/**
* File was generated by animation packager.
*/
#ifndef		_FONT_BODY_SMALL_200_IPAD_H
#define		_FONT_BODY_SMALL_200_IPAD_H


#define		FONT_BODY_SMALL_200_IPAD_NUM_MODULES				94


#define		FONT_BODY_SMALL_200_IPAD_NUM_FRAMES				94


#define		FONT_BODY_SMALL_200_IPAD_NUM_ANIMS				0


#endif