/**
* File was generated by animation packager.
*/
#ifndef		_FONT_FEVER_01_I6_H
#define		_FONT_FEVER_01_I6_H


#define		FONT_FEVER_01_I6_NUM_MODULES				14
#define		FONT_FEVER_01_I6_MODULE_SB				0
#define		FONT_FEVER_01_I6_MODULE_SCORE				1


#define		FONT_FEVER_01_I6_NUM_FRAMES				28
#define		FONT_FEVER_01_I6_FRAME_SB				26


#define		FONT_FEVER_01_I6_NUM_ANIMS				0


#endif