/**
* File was generated by animation packager.
*/
#ifndef		_FONT_COMBO_01_I6_H
#define		_FONT_COMBO_01_I6_H


#define		FONT_COMBO_01_I6_NUM_MODULES				13


#define		FONT_COMBO_01_I6_NUM_FRAMES				27


#define		FONT_COMBO_01_I6_NUM_ANIMS				0


#endif