/**
* File was generated by animation packager.
*/
#ifndef		_FONT_SCORE_01_I6_H
#define		_FONT_SCORE_01_I6_H


#define		FONT_SCORE_01_I6_NUM_MODULES				10


#define		FONT_SCORE_01_I6_NUM_FRAMES				25


#define		FONT_SCORE_01_I6_NUM_ANIMS				0


#endif