/**
* File was generated by animation packager.
*/
#ifndef		_FONT_TIMELINE_01_I6_H
#define		_FONT_TIMELINE_01_I6_H


#define		FONT_TIMELINE_01_I6_NUM_MODULES				14


#define		FONT_TIMELINE_01_I6_NUM_FRAMES				26


#define		FONT_TIMELINE_01_I6_NUM_ANIMS				0


#endif