/**
* File was generated by animation packager.
*/
#ifndef		_FONT_LOADING_01_I6_H
#define		_FONT_LOADING_01_I6_H


#define		FONT_LOADING_01_I6_NUM_MODULES				11


#define		FONT_LOADING_01_I6_NUM_FRAMES				25


#define		FONT_LOADING_01_I6_NUM_ANIMS				0


#endif