/**
* File was generated by animation packager.
*/
#ifndef		_HUD_LEAF_01_I6_H
#define		_HUD_LEAF_01_I6_H


#define		HUD_LEAF_01_I6_NUM_MODULES				4


#define		HUD_LEAF_01_I6_NUM_FRAMES				4


#define		HUD_LEAF_01_I6_NUM_ANIMS				0


#endif