/**
* File was generated by animation packager.
*/
#ifndef		_HUD_WEARTHER_01_I6_H
#define		_HUD_WEARTHER_01_I6_H


#define		HUD_WEARTHER_01_I6_NUM_MODULES				6
#define		HUD_WEARTHER_01_I6_MODULE_ANH_NANG				0
#define		HUD_WEARTHER_01_I6_MODULE_LIGHT				5


#define		HUD_WEARTHER_01_I6_NUM_FRAMES				6
#define		HUD_WEARTHER_01_I6_FRAME_ANH_NANG				0
#define		HUD_WEARTHER_01_I6_FRAME_LIGHT				1
#define		HUD_WEARTHER_01_I6_FRAME_LEAF				2


#define		HUD_WEARTHER_01_I6_NUM_ANIMS				0


#endif